version: '3'
services:
  web:
    build:
      context: ./flask
      dockerfile: Dockerfile
    networks:
      - default
    ports:
      - 3001:3001
    restart: always
    environment:
      PORT: 3001
    depends_on:
      - db
      
  db:
    image: postgres
    networks:
      - default
    volumes:
      - /home/wcap/tmp/event-maker:/var/lib/postgresql/data/
    ports:
      - 5432:5432
    environment:
      PORT: 5432